/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import interacters.vacancy;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import wallpark.connect_manager;

/**
 *
 * @author joker
 */
public class _list extends javax.swing.JFrame {

    /**
     * Creates new form _list
     */
    public _list() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Vlist = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallpark");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Vlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vaga", "Estado", "Ocupado por"
            }
        ));
        jScrollPane1.setViewportView(Vlist);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    
    
    public void lister()
    {    
        connect_manager man_co = new connect_manager();      
        DefaultTableModel model = (DefaultTableModel) Vlist.getModel();
        
        model.setNumRows(0);
        
        ArrayList<vacancy> listen = man_co.viewer();
        
        for (int i = 0; i < listen.size(); i++) 
        {            
            model.addRow(new  Object[]
                {
                    listen.get(i).getId(),
                    listen.get(i).getDisponibilit(),
                    listen.get(i).getPid()
                  });             
         }          
     }      
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Vlist;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
