/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.JOptionPane;
import wallpark.connect_manager;

/**
 *
 * @author joker
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        pass_field = new javax.swing.JTextField();
        send_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallpark");
        setMinimumSize(new java.awt.Dimension(516, 319));
        setPreferredSize(new java.awt.Dimension(400, 385));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        login.setText("LOGIN");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        user.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        user.setText("Úsuario");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        password.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        password.setText("Senha");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        user_field.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        getContentPane().add(user_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 210, -1));

        pass_field.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        pass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(pass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 210, -1));

        send_button.setBackground(new java.awt.Color(102, 255, 0));
        send_button.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        send_button.setForeground(new java.awt.Color(0, 102, 0));
        send_button.setText("CONFIRMAR");
        send_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(send_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 308, -1, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_fieldActionPerformed

    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        
        connect_manager user = new connect_manager();
        vehicle_management maen = new vehicle_management();
        
        if(user.verify_employ(user_field.getText(), pass_field.getText()))
        {
            setVisible(false);
            maen.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ÚSUARIO OU SENHA INCORRETOS"); 
        }
    }//GEN-LAST:event_send_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel login;
    private javax.swing.JTextField pass_field;
    private javax.swing.JLabel password;
    private javax.swing.JButton send_button;
    private javax.swing.JLabel user;
    private javax.swing.JTextField user_field;
    // End of variables declaration//GEN-END:variables
}
