/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import wallpark.connect_manager;

/**
 *
 * @author joker
 */
public class remove_vehicle extends javax.swing.JFrame {

    /**
     * Creates new form remove_vehicle
     */
    public remove_vehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        info_field = new javax.swing.JTextField();
        send_field = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallpark");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("RETIRADA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        info.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        info.setForeground(new java.awt.Color(0, 0, 0));
        info.setText("Informe a placa do veiculo:");
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        info_field.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        getContentPane().add(info_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 150, 30));

        send_field.setBackground(new java.awt.Color(51, 204, 0));
        send_field.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        send_field.setForeground(new java.awt.Color(51, 102, 0));
        send_field.setText("CONFIRMAR");
        send_field.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(send_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void send_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_fieldActionPerformed
        
        String Can_plate = info_field.getText();
        connect_manager man_co = new connect_manager();
        
        man_co.deleter(Can_plate);
    }//GEN-LAST:event_send_fieldActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel info;
    private javax.swing.JTextField info_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton send_field;
    // End of variables declaration//GEN-END:variables
}
