/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import interacters.vacancy;
import interacters.vehicle;
import javax.swing.JOptionPane;
import wallpark.alter_vehicle;
import wallpark.connect_manager;

/**
 *
 * @author joker
 */
public class updated_vehicle extends javax.swing.JFrame {

    /**
     * Creates new form updated_vehicle
     */
    public updated_vehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        re_button = new javax.swing.JButton();
        M = new javax.swing.JLabel();
        P_field = new javax.swing.JTextField();
        new_color = new javax.swing.JTextField();
        new_model = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallpark");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ALTERAR INFORMAÇÕES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        P.setText("Placa(identificador):");
        getContentPane().add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        C.setText("Nova cor:");
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, -1));

        re_button.setBackground(new java.awt.Color(204, 204, 0));
        re_button.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        re_button.setForeground(new java.awt.Color(102, 102, 0));
        re_button.setText("ALTERAR");
        re_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        re_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(re_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        M.setText("Novo Modelo:");
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        P_field.setText(" ");
        getContentPane().add(P_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        new_color.setText(" ");
        getContentPane().add(new_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 220, -1));

        new_model.setText(" ");
        getContentPane().add(new_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 190, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void re_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_buttonActionPerformed
          
        alter_vehicle altering = new  alter_vehicle();                
        String plate = P_field.getText();  
                
        
        
        if ("".equals(plate)) 
        {
            JOptionPane.showMessageDialog(null,"PLACA DE VEICULO NULO OU INVÁLIDO: alteração de dados não foi efetuada e a janela será fechada, favor inserir cpf na próxima vez");
        }
        else
        {
            altering.verify_plate(plate);            
        }                
        
        
        if ("".equals(new_color.getText()))
        {
            altering.alter(plate,new_model.getText(),1);
        }
        else if ("".equals(new_model.getText())) 
        {
            altering.alter(plate,new_color.getText());
        }        
        else
        {
            altering.alter(plate,new_color.getText(),new_model.getText());
        }
        
        
        setVisible(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_re_buttonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C;
    private javax.swing.JLabel M;
    private javax.swing.JLabel P;
    private javax.swing.JTextField P_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField new_color;
    private javax.swing.JTextField new_model;
    private javax.swing.JButton re_button;
    // End of variables declaration//GEN-END:variables
}
