/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import interacters.vacancy;
import interacters.vehicle;
import wallpark.connect_manager;

/**
 *
 * @author joker
 */
public class vehicle_management extends javax.swing.JFrame {

    /**
     * Creates new form vehicle_management
     */
    public vehicle_management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        plate = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        service = new javax.swing.JLabel();
        color_field = new javax.swing.JTextField();
        plate_field = new javax.swing.JTextField();
        model_field = new javax.swing.JTextField();
        service_field = new javax.swing.JTextField();
        send_button = new javax.swing.JButton();
        up_button = new javax.swing.JButton();
        remove_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        list_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallpark");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GERENCIAMENTO DE VEICULOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        color.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        color.setText("Cor");
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        plate.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        plate.setText("Placa");
        getContentPane().add(plate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        model.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        model.setText("Modelo");
        getContentPane().add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        service.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        service.setText("Serviço");
        getContentPane().add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        color_field.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        getContentPane().add(color_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, -1));

        plate_field.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        getContentPane().add(plate_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, -1));

        model_field.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        getContentPane().add(model_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 210, -1));

        service_field.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        getContentPane().add(service_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 210, -1));

        send_button.setBackground(new java.awt.Color(102, 255, 0));
        send_button.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        send_button.setForeground(new java.awt.Color(51, 102, 0));
        send_button.setText("ADICIONAR");
        send_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(send_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        up_button.setBackground(new java.awt.Color(204, 204, 0));
        up_button.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        up_button.setForeground(new java.awt.Color(102, 102, 0));
        up_button.setText("MUDAR INFO");
        up_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(up_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 350, -1, -1));

        remove_button.setBackground(new java.awt.Color(255, 51, 0));
        remove_button.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        remove_button.setForeground(new java.awt.Color(153, 0, 0));
        remove_button.setText("RETIRAR");
        remove_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(remove_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 620, 30));

        list_button.setBackground(new java.awt.Color(0, 102, 255));
        list_button.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        list_button.setForeground(new java.awt.Color(0, 51, 153));
        list_button.setText("CHECAR");
        list_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(list_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 390, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        vehicle mobil = new  vehicle();
        vacancy day = new vacancy();
        connect_manager co_man = new connect_manager();        
        String plate = plate_field.getText();        
                
        
        if (plate.length() > 5)
        {
            plate = plate.substring(0,4);
            mobil.setPlate(plate);
        }
        else
        {
            mobil.setPlate(plate);
        }
                
                
        mobil.setColor(color_field.getText());
        mobil.setModel(model_field.getText());
        day.setDisponibilit(service_field.getText());
        
        
        co_man.sign_in(mobil,day);
    }//GEN-LAST:event_send_buttonActionPerformed

    private void list_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_buttonActionPerformed
        
        _list assembly = new _list();
        connect_manager Tview = new connect_manager();
        
        Tview.viewer();
        assembly.lister();
        
        assembly.setVisible(true);
        assembly.setDefaultCloseOperation(assembly.DISPOSE_ON_CLOSE); 
        
    }//GEN-LAST:event_list_buttonActionPerformed

    private void up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_buttonActionPerformed
        
        updated_vehicle up = new updated_vehicle();
        
        up.setVisible(true);
        up.setDefaultCloseOperation(up.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_up_buttonActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        
        remove_vehicle del = new remove_vehicle();
        
        del.setVisible(true);
        del.setDefaultCloseOperation(del.DISPOSE_ON_CLOSE); 
        
    }//GEN-LAST:event_remove_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicle_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicle_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicle_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicle_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehicle_management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel color;
    private javax.swing.JTextField color_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton list_button;
    private javax.swing.JLabel model;
    private javax.swing.JTextField model_field;
    private javax.swing.JLabel plate;
    private javax.swing.JTextField plate_field;
    private javax.swing.JButton remove_button;
    private javax.swing.JButton send_button;
    private javax.swing.JLabel service;
    private javax.swing.JTextField service_field;
    private javax.swing.JButton up_button;
    // End of variables declaration//GEN-END:variables
}
